### ISSUE TITLE
Scroll to top does not work on Firefox, but does with Chrome and Edge

### ISSUE THREAD

**Issue by tmpg** [davesnx/scrollto-with-animation#15]
It seems that this piece of code works on Edge and Chrome but not Firefox:

```
      scrollToWithAnimation(
        document.body, // element to scroll
        'scrollTop', // direction to scroll
        0, // target scrollY (0 means top of the page)
        500, // duration in ms
        'easeInOutCirc',
        function () { // callback function that runs after the animation (optional)
        console.log('done!')
       }
      );
```

Pretty much the example... When a button is clicked to scroll to the top, which executes this function, it does nothing but the call back function fires. Identifying that it did complete.

I am using this with React v15.2

Let me know what your thoughts are.

Many thanks,
Tim

**Comment by davesnx** [comment]
Seems pretty random, I tried my program with Firefox and works perfectly. 
Can you try to not use `target scrollY: 0`? Seems like there's some pixel difference on the demo in Firefox by CSS.

That make sense? @tmpg 
Sorry for answer than late.
Thanks for open a issue!

**Comment by tmpg** [comment]
What would I use instead of `target scrollY: 0`?

Thanks

**Comment by davesnx** [comment]
Try to scroll until 200px or something

**Comment by tmpg** [comment]
Still doesn't work: 

```
  scrollToWithAnimation(
    document.body, // element to scroll
    'scrollTop', // direction to scroll
    200, // target scrollY (0 means top of the page)
    500, // duration in ms
    'easeInOutCirc'
  );
```

I am using this with meteor 1.4.1 and react 15.3.1

**Comment by Rheed** [comment]
@tmpg maybe its a bit late, but just in case. Firefox and IE can't activate the scrolling due to how they detect it, and you need to use document.documentElement instead of document.body. So you will have to play around with that

Depends a bit on how are you managing the whole scrolling, if its an inner component or the whole document itself, so you will need to either fix that or play around with that :)

**Comment by davesnx** [comment]
It's been a while since this remains open, we highly use the lib in 4 Applications and we don't have any problem Firefox so far. 

Thanks for open the issue @tmpg
