### ISSUE TITLE
scrollTo both

### ISSUE THREAD

**Issue by Mottie** [davesnx/scrollto-with-animation#19]
The browser [scrollTo](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) function allows scrolling to a x *and* y position on a page.

Please consider supporting a `scrollTo` that animates in both directions simultaneously.

```js
scrollToWithAnimation(
    document.body,  // element to scroll
    'scrollTo'      // scroll both x & y position
    [x, y],         // array of x & y position
    duration,       // duration in ms
    [easeX, easeY], // different easing per direction
    done()
);
```

**Comment by julkue** [comment]
👍 Useful

**Comment by davesnx** [comment]
Thanks @Mottie & @julmot 

The implementation is trivial, but my concern is more about changing the API. Also, specifying and array for pass two values isn't the best way to do it. Probably an object makes more sense `{ scrollToX, scrollToY }`, but again, sending different easing for each direction also seems weird to me. 

I keep on eye on this cases to growth the way of sending parameters into `scrollToWithAnimation` and seriously consider to pass an Object and specify all of this options into it.

Let me take a look this week what can I do.

**Comment by Mottie** [comment]
I only brought up the separation of easings because jQuery supports it in their [`animate` function](http://api.jquery.com/animate/) `specialEasing` option.

I have been considering rewriting my very-outdated [visualNav plugin](https://github.com/Mottie/visualNav) to use plain javascript. You can see the use of separate easings in [this demo](http://mottie.github.io/visualNav/horiz-vert.html#projects) - click on "Projects" with the "Home" panel showing.

**Comment by davesnx** [comment]
Hey @julmot and @Mottie 

I know that seems a good use case for `scroll-with-animation` but I'm concern to change to much the purpose of this module is being simple.

As a possible work around, you could fork it and try to call requestAnimationFrame with the 2 values or in case that you want to just make `visualNav` in vanilla you could use [`async.parallel`](https://www.npmjs.com/package/async-parallel) (that is just the parallel method of [async](https://github.com/caolan/async)).

Hope that this helps your issue. If you still want this as being part of this module I would accept any PR with this change.
Thanks for open it.
