### ISSUE TITLE
Take an options object instead of 6 discrete parameters

### ISSUE THREAD

**Issue by Tvrqvoise** [davesnx/scrollto-with-animation#22]
Hello!  Love the library.  One tweak I'd be happy to see would be an options object instead of a parameters list.  That would let us leave the defaults when needed, and would make things a little bit more readable for consumers.  Could potentially be done in a backwards compatible manner by sniffing for the existence of the scrollTop property on the first parameter.

Thanks for the great work.

**Comment by davesnx** [comment]
Hey @Tvrqvoise,

Thanks! Good observation, it's true. We can make the first parameter being and object without breaking compatibility.

Want to make a PR with that change?
If not I will take a look in a few days!

**Comment by Tvrqvoise** [comment]
Gladly, I'll make a PR.  Would you like me to throw in a deprecation notice to the console when the user uses multi params, or should we explicitly support both?

**Comment by davesnx** [comment]
I would say, support both for 4.x.x and show the deprecation message. In case that we move to v5 we can throw an error
