### ISSUE TITLE
Importing package.json leaks unwanted info into a bundle

### ISSUE THREAD

**Issue by nirazul** [davesnx/scrollto-with-animation#23]
I'm using `scrollto-with-animation` in a project that's compiled with webpack.

I've noticed that my local machine path is being exposed because this plugin requires the local `package.json` and npm adds the following information to the file:

`'_where': '/path/to/local/repository'`

While this information is not very private, it's certainly undesirable to expose this in source code that is being published to production. I think it's better to just hardcode `name`, `version`, `repository` instead of requiring the `package.json` file.

**Comment by davesnx** [comment]
Good spot. I'm certainly not super happy about requiring the `package.json` into production code.

Do you mind create a PR for this? 

Thanks for the issue

**Comment by nirazul** [comment]
@davesnx 
Are you ok with hardcoding it for the moment? Then I'm happy to provide a PR. Else we need to discuss first, how to replace the data.

**Comment by nirazul** [comment]
@davesnx 
ping 😬

**Comment by davesnx** [comment]
Yes, I'm happy to hardcode it.

Sorry for not responding earlier :(

**Comment by nirazul** [comment]
No problem, happens to me all the time ^^
