### ISSUE TITLE
Demo Question

### ISSUE THREAD

**Issue by anthonyaam** [davesnx/scrollto-with-animation#24]
How does the demo work? I'm on Chrome and I don't see any button to trigger scrolling. As I scroll up and down the elements appears to natively scroll. I see the FPS counter go from 60 to 0 then to 60 again after scrolling. Sorry for being so lost and thanks for the help.

Demo: http://scrollto-with-animation.surge.sh/

**Comment by karltaylor** [comment]
+1.

When I go to the Demo, nothing happens? I am not sure how the scroll is triggered.

**Comment by davesnx** [comment]
Hey, I will re-do the demo. Depends on the focus it works automatically. 
I will take a look!

Thanks!
