### ISSUE TITLE
Remove eases

### ISSUE THREAD

**Issue by stevenvachon** [davesnx/scrollto-with-animation#27]
They're unnecessary bloat. Consumers of this library can customize using [eases](https://npmjs.com/eases).

**Comment by davesnx** [comment]
Hey @stevenvachon 

I decided for this library to prioritize developer experience over 434 bytes gzipped (over 2.8kb gzipped). 

I'm happy to release a new version that allows to pass any ease fn to allow more flexibility, but still think that the easing would live inside the lib. Luckly there are tools like any modern bundler can tree shake the non-used easings.

Thanks for reporting it.
