### ISSUE TITLE
tries to import missing file "package-info.json"

### ISSUE THREAD

**Issue by wagich** [davesnx/scrollto-with-animation#54]
The main file (entrypoint) at `lib/index.js` tries to `require('./package-info.json')` which fails because the file does not exist in the `lib` folder (it only exists in `src`).

This seems to be a bug introduced by the 4.5.3 release.
Maybe the data from package-info.json could be inlined by the build process?

**Comment by davesnx** [comment]
Yes, let me fix that!

**Comment by davesnx** [comment]
Should be fixed at 4.5.4, Thanks for reporting @wagich
