### ISSUE TITLE
how about scrollLeft option?

### ISSUE THREAD

**Issue by jackyon** [davesnx/scrollto-with-animation#7]
hi, just curious about if scrollLeft option available?

**Comment by davesnx** [comment]
Hello @jackyon, thanks for the issue!
It wasn't on the 'scope' of this lib, but It's pretty easy to implement, do you want to do a PR?

**Comment by jackyon** [comment]
hi @davesnx 
already PR, plz progress, also release to the npm version, so that I can use it.

thx!

**Comment by davesnx** [comment]
I merge it
